# Default values for app.
replicaCount: 1

image:
  registry: docker.io
  repository: parcial
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix
  tls: []

config:
  dbHost: "parcial-postgresql"
  dbPort: "5432"
  dbName: "parcialdb"
  dbUser: "myuser"

secret:
  dbPassword: "mypass"

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi