# values-prod.yaml - valores para entorno prod
replicaCount: 3

image:
  repository: parcial
  tag: prod

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    memory: "512Mi"

env:
  - name: ENVIRONMENT
    value: "prod"